### ISSUE TITLE
这个好像显示不了韩文，不知道能不能加上韩文显示

### ISSUE THREAD

**Issue by yanghui1228** [HowardZorn/Souce-Han-SimSun#2]

**Comment by HowardZorn** [comment]
因为[Dream Han Serif](https://github.com/Pal3love/dream-han-cjk)并无发布“SC”类别的字体。原来的思源宋体SC是含有韩文的。你可以找一个思源宋体SC的ttf变体来做这个事情。

**Comment by HowardZorn** [comment]
你可以下载[Source Han Serif](https://github.com/adobe-fonts/source-han-serif/releases)仓库里的Language Specific OTFs Simplified Chinese发布版，然后替换我用的Dream Han Serif，就可以得到一个含有韩文字形的字体文件了。

但是我可能暂时不会加入韩文，谢谢关注这个仓库的问题。
